### PR TITLE
[TBCM-222] Flex column outside click close

### PR DESCRIPTION
**Pull request by JGH-EY**

### CODE REVIEW

**Comment by JGH-EY** [comment]
I see the issue. I will address this now.

**Review by kushal-arora-fw — COMMENTED** [review]
Great! This looks good and works well with the UserDropdown. 

However, I was thinking rather than forward passing ref from UserDropdown, is there a way you could think of to make it work generic inside the AppMenu enabling all menus be closed when clicked outside? 

Ref: Have a look at the gaps and optimization screen -> Occupation List button; It also leverages the same AppMenu and doesn't close when clicked outside either.

**Review by dbayly-freshworks — APPROVED** [review]
This looks ok to me.

**Review by kushal-arora-fw — APPROVED** [review]
Great! This is fantastic. Thanks James

**Pull request merged**
